### ISSUE TITLE
Slim support

### ISSUE THREAD

**Issue by ramaboo** [m-basov/mjml-ruby#7]
I tried changing extensions with no luck :(

```
# mailers/user_mailer/receipt.html.mjml
<mj-column>
  <mj-text>
    Hello this text is inside the view
  </mj-text>
</mj-column>
```
Works fine. I expected this to work though:

```
# mailers/user_mailer/receipt.html.mjml.slim
mj-column
  mj-text Hello this text is inside the view
```

I get the error:
```
Missing template user_mailer/receipt with "mailer". Searched in:
  * "user_mailer"
```

Is there something special I have to do to enable other template languages. Usually with rails you can sort of chain templates indefinitely and they get passed own the chain to each successive handler.

**Comment by m-basov** [comment]
@ramaboo AFAIK chaining extensions is working only with assets(Sprockets). Email templates(and templates in general) are not processed with Sprockets because extensions means `Content-Type` and `pre-processor`.

```
       receipt.html.mjml
                |     |
Content-Type ---|     |--- pre-processor
```

There are undocumented way to use slim, you need to add extension `*.html.mjmlslim`(or `*.html.mjmlhaml` for HAML) but I am in doubt about this way because extension is not standard and will not works fine with some text editors.

**Comment by ramaboo** [comment]
Humm I thought the pre-processor chaining worked everywhere. Ahh well the .mjmlslim file extension seemed to work so that's great and atom is easy to configure to view it as a slim file thanks:).
